# Generated by Django 3.2.12 on 2022-03-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_pick_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='win',
            field=models.BooleanField(null=True),
        ),
    ]
